[package]
name = "kindle-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
chess-core = { path = "../chess-core" }
chess-render = { path = "../chess-render" }
fbink-sys = { path = "../fbink-sys" }

[lints]
workspace = true
