[package]
name = "kindle-chess"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
chess-core = { path = "../../crates/chess-core" }
chess-render = { path = "../../crates/chess-render" }
kindle-platform = { path = "../../crates/kindle-platform" }

[lints]
workspace = true
